## Arrays
In addition to simple variables programming languages provide a lot of different more complex **data types** that make it easier to express high-evel ideas.

One if the first of these is the array.

Arrays are a way to hold multiple values of variables (normally of the same type e.g. float, integer) as a single named container variable, in a way that can be _indexed_. The individual values within an array are called "elements" of the array. The index ranges over which an array can be accessed are called "bounds".

In scientific computing in Python the most common practice is to use arrays from the Python (Numpy package)[https://en.wikipedia.org/wiki/NumPy]. Numpy started life in part as work in an MIT graduate student project ( https://aip.scitation.org/doi/pdf/10.1063/1.4822400 ) in the mid 1990s!. 

#### Lets create some Numpy arrays and access element 3 in each array.
 
we use four different functions from Numpy that are described somewhat tersely at

   * https://numpy.org/doc/stable/reference/generated/numpy.ones.html
   * https://numpy.org/doc/stable/reference/generated/numpy.empty.html
   * https://numpy.org/doc/stable/reference/generated/numpy.zeros.html
   * https://numpy.org/doc/stable/reference/generated/numpy.full.html
   
respectively. 

np.ones() creates an array of a given size with elements all set to the value one initially.  
np.empty() creates an array of a given size with elements unset initially (i.e. locations in memory are uninitialized).  
np.zeros() creates an array of a given size with elements all set to the value zero initially.  
np.full() creates an array of a given size with elements all set to the value zero initially.

In [53]:
import numpy as np
nel=10
a1=np.ones(nel)
a2=np.empty(nel)
a3=np.zeros(nel)
a4=np.full(nel,12,int)
a5=np.array([1,2,3.,"hello"])

In [44]:
print(" a1[3] = ",a1[3]) # Access element 3
print(" a2[3] = ",a2[3]) # Access element 3
print(" a3[3] = ",a3[3]) # Access element 3
print(" a4[3] = ",a4[3]) # Access element 3
print(" a5[3] = ",a5[3]) # Access element 3

 a1[3] =  1.0
 a2[3] =  1.0
 a3[3] =  0.0
 a4[3] =  12
 a5[3] =  hello


In [24]:
# Indexing arrays in Python starts with element 0 and ends with "number of elements - 1".
la=len(a1)
a1[0]=7
a1[la-1]=12
print(a1)

[ 7.  1.  1.  1.  1.  1.  1.  1.  1. 12.]


In [25]:
# Indexing outside the "bounds" of an array gives an error
print(a1[la])

IndexError: index 10 is out of bounds for axis 0 with size 10

In [55]:
# Arrays have "types", which affects performance and behvior. 
# In general the best performance requires simple and uniform types.
print( a1[0]*a1[1] )
print( a5[0]*a5[1] )

1.0


TypeError: can't multiply sequence by non-int of type 'numpy.str_'

In [28]:
# Arrays can be multi-dimensional
# A two dimensional array can be created as follows
nelI=4
nelJ=3
a_2d=np.ones((nelI,nelJ))
print(a_2d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [39]:
# An eight dimensinal array !
a_8d=np.ones((3,3,3,3,3,3,3,3))
print("The size of array a_8d is the product of all its dimensions. It equals =", a_8d.size)
print(a_8d)

The size of array a_8d is the product of all its dimensions. It equals = 6561
[[[[[[[[1. 1. 1.]
       [1. 1. 1.]
       [1. 1. 1.]]

      [[1. 1. 1.]
       [1. 1. 1.]
       [1. 1. 1.]]

      [[1. 1. 1.]
       [1. 1. 1.]
       [1. 1. 1.]]]


     [[[1. 1. 1.]
       [1. 1. 1.]
       [1. 1. 1.]]

      [[1. 1. 1.]
       [1. 1. 1.]
       [1. 1. 1.]]

      [[1. 1. 1.]
       [1. 1. 1.]
       [1. 1. 1.]]]


     [[[1. 1. 1.]
       [1. 1. 1.]
       [1. 1. 1.]]

      [[1. 1. 1.]
       [1. 1. 1.]
       [1. 1. 1.]]

      [[1. 1. 1.]
       [1. 1. 1.]
       [1. 1. 1.]]]]



    [[[[1. 1. 1.]
       [1. 1. 1.]
       [1. 1. 1.]]

      [[1. 1. 1.]
       [1. 1. 1.]
       [1. 1. 1.]]

      [[1. 1. 1.]
       [1. 1. 1.]
       [1. 1. 1.]]]


     [[[1. 1. 1.]
       [1. 1. 1.]
       [1. 1. 1.]]

      [[1. 1. 1.]
       [1. 1. 1.]
       [1. 1. 1.]]

      [[1. 1. 1.]
       [1. 1. 1.]
       [1. 1. 1.]]]


     [[[1. 1. 1.]
       [1. 1. 1.]
       [1. 1. 1.]]

      [[1. 1. 